name: Release Transaction Counter Plugin
on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        type: string
        description: "Release Version"
      next_version:
        type: string
        description: "Next Development Version"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn clean install -DskipTests=true


      
