name: Release Transaction Counting Handler
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build with Maven
        working-directory: ./counter
        run: mvn package --file pom.xml
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          directory: ./counter
          server_id: wso2.releases
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
